# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Y4g_DO_8ZOtHOCoD0_grPYAS6_rKISz

**Data Science Tools and Ecosystem**

In this notebook, Data Science Tools and Ecosystem are summarized.

Some of the popular languages that Data Scientists use are:

*   python
*   R

Some of the commonly used libraries used by Data Scientists include:


*   pandas
*   numpy
*   sklearn
*   tenserflow

### Data Science Tools

| Data Science Tools |
|--------------------|
| Jupyter Notebook  |
| RStudio          |
| Apache Zeppelin  |

### Below are a few examples of evaluating arithmetic expressions in Python

1. **Addition**: `3 + 5 = 8`  
2. **Subtraction**: `10 - 4 = 6`  
3. **Multiplication**: `6 * 7 = 42`  
4. **Division**: `20 / 4 = 5.0`  
5. **Exponentiation**: `2 ** 3 = 8`  
6. **Modulus (Remainder)**: `10 % 3 = 1`  
7. **Floor Division**: `15 // 4 = 3`
"""

# This is a simple arithmetic expression to multiply then add integers.
result = (3 * 4) + 5
print(result)  # Expected output: 17

"""**Objectives:**  

- List popular languages for Data Science  
- Identify commonly used libraries in Data Science  
- Demonstrate basic arithmetic expressions in Python  
- Convert minutes to hours using Python  
- Create and format Markdown cells in Jupyter Notebook

## Author  
John Doe
"""